# Publish resources
name: "🚀 publish"

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*"
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src'

jobs:

  # Generate dist
  dist:
    runs-on: ubuntu-latest

    steps:

      # Pull Source Code
      -
        name: Checkout
        uses: actions/checkout@v2

      # Use nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # Install npm packages
      - run: npm install

      # Build dist
      - run: rm -rf dist/.git* # delete .git* files
      - run: npm run all

      # publish release
      - run: echo ${{ github.sha }} >> Release.txt
      - run: mv LICENSE LICENSE.txt
      - name: "📦 Github Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            src/*.js
            dist/*.js
            package.json
            Release.txt
            LICENSE.txt
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to npm
      - name: "📦 publish to npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: true

      # Publish to github npm
      - name: "📦 publish to github npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          access: "public"
          registry: "https://npm.pkg.github.com"
          check-version: true