# Publish resources
name: "🚀 publish"

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*"
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src'

jobs:

  # Generate dist
  dist:
    runs-on: ubuntu-latest

    steps:

      # Pull Source Code
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Use nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # Install npm packages
      - run: npm install

      # dist setup
      - run: rm -rf dist/.git* # delete .git* files
      - run: echo ${{ env.RELEASE_VERSION }} >> Release.txt
      - run: mv LICENSE LICENSE.txt
      - run: sed -i -e 's/REL_VER_NUMBER/${{ env.RELEASE_VERSION }}/g' src/plugin.js

      # Build dist
      - run: npm run all

      # Publish to npm
      - name: "📦 publish to npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: true

      # Publish to github npm
      - name: "📦 publish to github npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          access: "public"
          registry: "https://npm.pkg.github.com"
          check-version: true

      # publish release
      - uses: papeloto/action-zip@v1
        with:
          files: |
            dist/plugin.js
            dist/plugin.min.js
            src/plugin.js
            package.json
            README.md
            LICENSE.txt
          recursive: false
          dest: dist.zip
      - run: sha256sum dist.zip >> dist.zip.sha256
      - run: md5sum dist.zip >> dist.zip.md5

      - name: "📦 Github Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: |
            dist.zip
            dist.zip.sha256
            dist.zip.md5