# Publish resources
name: "🚀 publish"

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src'

  # workflow_dispatch:
  #   inputs:
  #     relVersion:
  #       description: 'Version'
  #       required: true

jobs:

  # Generate dist
  dist:
    runs-on: ubuntu-latest

    steps:

      # Pull Source Code
      -
        name: Checkout
        uses: actions/checkout@v2

      # Use nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # Install npm packages
      - run: npm install

      # Build dist
      - run: npm run all

      # Publish to npm
      - name: "📦 publish to npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: true

      # Publish to github npm
      - name: "📦 publish to github npm"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          access: "public"
          registry: "https://npm.pkg.github.com"
          check-version: true